export const projects = [
  {
    year: 2026,
    project: "Car Window Tint Near Me",
    madeAt: "IBX Digital",
    builtWith: ["Landing Pages", "WordPress", "Bricks", "ACF"],
    link: "www.car-window-tint-near-me.com",
    url: "https://car-window-tint-near-me.com/",
  },
  {
    year: 2026,
    project: "Home and Office Window Tinting",
    madeAt: "IBX Digital",
    builtWith: ["Landing Pages", "WordPress", "Elementor", "ACF"],
    link: "www.homeandofficewindowtinting.com",
    url: "https://homeandofficewindowtinting.com/",
  },
  {
    year: 2026,
    project: "Ceramic Coating Services",
    madeAt: "IBX Digital",
    builtWith: ["Landing Pages", "WordPress", "Elementor", "ACF"],
    link: "www.ceramic-coating.services",
    url: "https://www.ceramic-coating.services/",
  },
  {
    year: 2026,
    project: "PPF Near You",
    madeAt: "IBX Digital",
    builtWith: ["Landing Pages", "WordPress", "Elementor", "ACF"],
    link: "www.ppfnearyou.com",
    url: "https://ppfnearyou.com/",
  },
  {
    year: 2025,
    project: "Rosewood Decks and Outdoor Living",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor", "ACF", "CPT"],
    link: "www.rosewooddecks.com",
    url: "https://www.rosewooddecks.com/",
  },
  {
    year: 2025,
    project: "Capital Autobahnd",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor"],
    link: "www.capitalautobahnd.com",
    url: "https://www.capitalautobahnd.com/",
  },
  {
    year: 2025,
    project: "BTX Auto Glass & Window Tint",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor"],
    link: "www.brownsvilleglasstint.com",
    url: "https://www.brownsvilleglasstint.com/",
  },
  {
    year: 2025,
    project: "Guardian Graphics",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor"],
    link: "www.guardiangraphics.net",
    url: "https://www.guardiangraphics.net/",
  },
  {
    year: 2025,
    project: "Locker Home Tint",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor"],
    link: "www.lockerhometint.com",
    url: "https://www.lockerhometint.com/",
  },
  {
    year: 2025,
    project: "Prime Auto Care Solutions",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor"],
    link: "www.pacstintandppf.com",
    url: "https://www.pacstintandppf.com/",
  },
  {
    year: 2025,
    project: "Replace Windshield",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor"],
    link: "www.replace-windshield.com",
    url: "https://replace-windshield.com/",
  },
  {
    year: 2025,
    project: "AP3 Services",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor"],
    link: "www.ap3-ppf.com",
    url: "https://www.ap3-ppf.com/",
  },
  {
    year: 2024,
    project: "Diamond Auto Boutique",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor"],
    link: "www.diamondautoboutique.com",
    url: "https://www.diamondautoboutique.com/",
  },
  {
    year: 2024,
    project: "EZ-Tint",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor"],
    link: "www.ez-tint.com",
    url: "https://www.ez-tint.com/",
  },
  {
    year: 2024,
    project: "Mammoth Machinery",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor"],
    link: "www.mammothmachine.com",
    url: "https://www.mammothmachine.com/",
  },
  {
    year: 2024,
    project: "Auto Concierge Auto Glass",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor"],
    link: "www.texaswindshieldandtint.com",
    url: "https://www.texaswindshieldandtint.com/",
  },
  {
    year: 2023,
    project: "Rahal Paint Protection",
    madeAt: "IBX Digital",
    builtWith: ["WordPress", "Elementor"],
    link: "www.rahalpaintprotection.com",
    url: "https://www.rahalpaintprotection.com/",
  },
];
